trigger: none

resources:
- repo: self

variables:
- group: Juice


stages:
- stage: DeployDevInfrastructure  
  displayName: Deploy Development Infrastructure
  jobs:
  - job: DeployInfrastructure
    displayName: Deploy Development Infrastructure
    pool: 
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Juice-Dev'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az deployment group create --resource-group $(DEVRESOURCEGROUP) --name deployinfradev --template-file $(Build.SourcesDirectory)\ARM-DevSecOps.json'
        addSpnToEnvironment: true

- stage: DeployProdInfrastructure  
  displayName: Deploy Production Infrastructure
  jobs:
  - job: DeployInfrastructure
    displayName: Deploy Production Infrastructure
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Juice-Prod'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az deployment group create --resource-group $(PRODRESOURCEGROUP) --name deployinfraprod --template-file $(Build.SourcesDirectory)\ARM-DevSecOps-Prod.json'
        addSpnToEnvironment: trues